// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.WebApps.Helper.PrivateDns
{
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// The Private DNS Management Client.
    /// </summary>
    public partial interface IPrivateDnsManagementClient : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Gets subscription credentials which uniquely identify Microsoft
        /// Azure subscription. The subscription ID forms part of the URI for
        /// every service call.
        /// </summary>
        string SubscriptionId { get; set; }

        /// <summary>
        /// Client Api Version.
        /// </summary>
        string ApiVersion { get; set; }


        /// <summary>
        /// Gets the IPrivateZones.
        /// </summary>
        IPrivateZones PrivateZones { get; }

        /// <summary>
        /// Gets the IVirtualNetworkLinks.
        /// </summary>
        IVirtualNetworkLinks VirtualNetworkLinks { get; }

        /// <summary>
        /// Gets the IRecordSets.
        /// </summary>
        IRecordSets RecordSets { get; }

    }
}
