// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.WebApps.Helper.Network.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// An array of available PrivateEndpoint types.
    /// </summary>
    public partial class AvailablePrivateEndpointTypesResult
    {
        /// <summary>
        /// Initializes a new instance of the
        /// AvailablePrivateEndpointTypesResult class.
        /// </summary>
        public AvailablePrivateEndpointTypesResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// AvailablePrivateEndpointTypesResult class.
        /// </summary>
        /// <param name="value">An array of available privateEndpoint
        /// type.</param>
        /// <param name="nextLink">The URL to get the next set of
        /// results.</param>
        public AvailablePrivateEndpointTypesResult(IList<AvailablePrivateEndpointType> value = default(IList<AvailablePrivateEndpointType>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets an array of available privateEndpoint type.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<AvailablePrivateEndpointType> Value { get; set; }

        /// <summary>
        /// Gets the URL to get the next set of results.
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; private set; }

    }
}
