// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.WebApps.Helper.Network.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Response for the ListPrivateDnsZoneGroups API service call.
    /// </summary>
    public partial class PrivateDnsZoneGroupListResult
    {
        /// <summary>
        /// Initializes a new instance of the PrivateDnsZoneGroupListResult
        /// class.
        /// </summary>
        public PrivateDnsZoneGroupListResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PrivateDnsZoneGroupListResult
        /// class.
        /// </summary>
        /// <param name="value">A list of private dns zone group resources in a
        /// private endpoint.</param>
        /// <param name="nextLink">The URL to get the next set of
        /// results.</param>
        public PrivateDnsZoneGroupListResult(IList<PrivateDnsZoneGroup> value = default(IList<PrivateDnsZoneGroup>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets a list of private dns zone group resources in a
        /// private endpoint.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<PrivateDnsZoneGroup> Value { get; set; }

        /// <summary>
        /// Gets the URL to get the next set of results.
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; private set; }

    }
}
