// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.WebApps.Helper.Network.Models
{

    /// <summary>
    /// Defines values for PublicIPAddressSkuTier.
    /// </summary>
    public static class PublicIPAddressSkuTier
    {
        public const string Regional = "Regional";
        public const string Global = "Global";
    }
}
