// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.WebApps.Helper.Network.Models
{

    /// <summary>
    /// Defines values for SecurityRuleProtocol.
    /// </summary>
    public static class SecurityRuleProtocol
    {
        public const string Tcp = "Tcp";
        public const string Udp = "Udp";
        public const string Icmp = "Icmp";
        public const string Esp = "Esp";
        public const string Asterisk = "*";
        public const string Ah = "Ah";
    }
}
