// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.WebApps.Helper.Network.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Response for the virtual networks GetUsage API service call.
    /// </summary>
    public partial class VirtualNetworkListUsageResult
    {
        /// <summary>
        /// Initializes a new instance of the VirtualNetworkListUsageResult
        /// class.
        /// </summary>
        public VirtualNetworkListUsageResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the VirtualNetworkListUsageResult
        /// class.
        /// </summary>
        /// <param name="value">VirtualNetwork usage stats.</param>
        /// <param name="nextLink">The URL to get the next set of
        /// results.</param>
        public VirtualNetworkListUsageResult(IList<VirtualNetworkUsage> value = default(IList<VirtualNetworkUsage>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets virtualNetwork usage stats.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<VirtualNetworkUsage> Value { get; private set; }

        /// <summary>
        /// Gets or sets the URL to get the next set of results.
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; set; }

    }
}
