// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.WebApps.Helper.Network.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Response for the ListVirtualNetworks API service call.
    /// </summary>
    public partial class VirtualNetworkListResult
    {
        /// <summary>
        /// Initializes a new instance of the VirtualNetworkListResult class.
        /// </summary>
        public VirtualNetworkListResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the VirtualNetworkListResult class.
        /// </summary>
        /// <param name="value">A list of VirtualNetwork resources in a
        /// resource group.</param>
        /// <param name="nextLink">The URL to get the next set of
        /// results.</param>
        public VirtualNetworkListResult(IList<VirtualNetwork> value = default(IList<VirtualNetwork>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets a list of VirtualNetwork resources in a resource
        /// group.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<VirtualNetwork> Value { get; set; }

        /// <summary>
        /// Gets or sets the URL to get the next set of results.
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; set; }

    }
}
