variables:
  DebugLocalBuildTasks: true

pool:
  name: Azure Pipelines
  vmImage: ubuntu-18.04

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - checkout: none
    - script: echo "A"

- stage: M
  jobs:
  - deployment: M1
    environment: 'azps'
    strategy: 
      runOnce:
        pre-deployment:
          steps:
          - task: ManualIntervention@8
            inputs:
              instructions: 'Test'
        deploy:
          steps:
          - script: echo "Deploy"

- stage: B
  jobs:
  - job: B1
    steps:
    - checkout: none
    - script: echo "B"