variables:
  DebugLocalBuildTasks: true

pool:
  name: Azure Pipelines
  vmImage: ubuntu-18.04

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - checkout: none
    - script: echo "A"

- stage: B
  jobs:
  - job: B1
    steps:
    - checkout: none
    - script: echo "B"