// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.WebApps.Helper.PrivateDns.Models
{

    /// <summary>
    /// Defines values for VirtualNetworkLinkState.
    /// </summary>
    public static class VirtualNetworkLinkState
    {
        public const string InProgress = "InProgress";
        public const string Completed = "Completed";
    }
}
